#pragma once

#include <string>
#include <nlohmann/json.hpp>

namespace jade {

/**
 * Root class for the config. Also corresponds exactly to the `config.json` file.
 */
struct ServerConfig {
    /**
     * The port the webserver runs at. Should differ from :80/:443 if using nginx or similar
     */
    short port = 6969;

    /**
     * The host the database is at. This must NOT include the port!
     * The port is currently not configurable, and assumes 5432
     * points to the correct postgres installation.
     */
    std::string dbHost = "localhost";

    std::string dbPassword;

    /**
     * The database name to connect to. This should usually not be modified outside
     * tests. The default name generated by the install script is `jade`, the default set
     * here.
     */
    std::string dbName = "jade";

    /**
     * The postgres user to connect under. Just like the database name, the default name
     * generated by the install script is `jade`.
     */
    std::string dbUsername = "jade";

    std::string getConnString();
};

inline void from_json(const nlohmann::json& i, ServerConfig& o) {
    i.at("dbPassword").get_to(o.dbPassword);

    if (i.contains("port")) {
        i.at("port").get_to(o.port);
    }
    if (i.contains("dbHost")) {
        i.at("dbHost").get_to(o.dbHost);
    }
    if (i.contains("dbName")) {
        i.at("dbName").get_to(o.dbName);
    }
    if (i.contains("dbUsername")) {
        i.at("dbUsername").get_to(o.dbUsername);
    }
}

}
